---
title: "Effective Viz"
---

```{r, message=FALSE}
library(tidyverse)
library(ggplot2)
library(leaflet)
library(gplots)
library(rnaturalearthhires)
library(rnaturalearth)
library(mosaic)
library(sf)
library(maps)
library(RColorBrewer)
library(socviz)
library(viridis)
```


Exercise 1: Professionalism

```{r}
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))
```

```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point()
```
```{r}
#| fig_cap: "How might we predict the 3pm temperature (temp3pm) by the 9am temperature (temp9am)"
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() +
  labs(title = "Predicting 3pm Temperatures 9am Temperatures", y= "Temperatures at 3 pm" , x= "Temperatures at 9 am" , color= "Location")
```

Exercise 2: Accessibility

```{r}
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)")  
```
Part A

```{r}
#| fig-cap: "Density plots of 3pm temperatures in 3 Australian locations."
#| fig-alt: "This vizualization is attempting to determine whether or not we can use temperatures at 3pm to predict temperatures at 9,. This is the link to the original csv file https://mac-stat.github.io/data/weather_3_locations.csv"

ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)")  
```

Partc C

```{r}
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)") + 
  scale_fill_viridis_d()    
```
```{r}
# In the color scale line:
# Change "fill" to "color" since we use color in the aes()
# Change "d" (discrete) to "c" (continuous) since maxtemp is on a continuous scale
ggplot(weather, aes(y = temp3pm, x = temp9am, color = maxtemp)) + 
  geom_point(alpha = 0.5) + 
  labs(x = "3pm temperature (Celsius)") + 
  scale_color_viridis_c()
```


